<footer class="relative z-0 mt-8 sm:mt-16 store-footer">
    <div aria-label="footer"
        class="store-footer__top pb-4 lg:pb-10 pt-10 lg:pt-22 space-y-8 divide-y divide-dashed divide-white/10">
        <div class="container xl:px-0 grid grid-cols-6 gap-10 lg:gap-6">
            <div
                class="col-span-6 lg:col-span-3 flex flex-col flex-1 items-center text-center lg:text-start lg:items-start space-y-6">
                <a href="https://printnes.co/" class="footer-logo">
                    <img src="https://cdn.salla.sa/cdn-cgi/image/fit=scale-down,width=400,height=400,onerror=redirect,format=auto/rDvVQ/v9NZdZgZCz4yasGy4UbUowoe5CvPN5Cet9FaJLNM.png"
                        alt="" class="img-fluid max-h-[70px]">
                </a>
                <p class="max-w-[400px] leading-6 mb-4">
                    PRINTNES مؤسسة سعودية معرّفه في وزارة التجارة "معروف" متخصصين في تصنيع المطبوعات وتقديم
                    خدمات التصميم الفريدة والمتميزة
                </p>
                <ul class="s-social-list">
                    <li class="s-social-link"><a href="https://www.instagram.com/printnes.co/" rel="noopener"
                            target="_blank" title="instagram" aria-label="instagram"><span
                                class="s-social-icon"><!-- Generated by IcoMoon.io -->
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                    viewBox="0 0 32 32">
                                    <title>instagram</title>
                                    <path
                                        d="M23 32h-14c-4.971 0-9-4.029-9-9v0-14c0-4.971 4.029-9 9-9v0h14c4.971 0 9 4.029 9 9v0 14c0 4.971-4.029 9-9 9v0zM9 2c-3.866 0-7 3.134-7 7v0 14c0 3.866 3.134 7 7 7v0h14c3.866 0 7-3.134 7-7v0-14c0-3.866-3.134-7-7-7v0zM16 24c-4.418 0-8-3.582-8-8s3.582-8 8-8c4.418 0 8 3.582 8 8v0c0 4.418-3.582 8-8 8v0zM16 10c-3.314 0-6 2.686-6 6s2.686 6 6 6c3.314 0 6-2.686 6-6v0c0-3.314-2.686-6-6-6v0zM25 9c-1.105 0-2-0.895-2-2s0.895-2 2-2c1.105 0 2 0.895 2 2v0c0 1.105-0.895 2-2 2v0zM25 7v0z">
                                    </path>
                                </svg>
                            </span></a></li>
                    <li class="s-social-link"><a href="https://www.tiktok.com/@printnes?_t=8YDOfIX3009&amp;_r=1"
                            rel="noopener" target="_blank" title="tiktok" aria-label="tiktok"><span
                                class="s-social-icon"><!-- Generated by IcoMoon.io -->
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                    viewBox="0 0 32 32">
                                    <title>tiktok</title>
                                    <path
                                        d="M29.046 7.029c-3.359 0-6.092-2.733-6.092-6.092 0-0.518-0.42-0.938-0.938-0.938h-5.021c-0.518 0-0.938 0.42-0.938 0.938v20.585c0 1.975-1.606 3.581-3.581 3.581s-3.581-1.606-3.581-3.581c0-1.975 1.606-3.581 3.581-3.581 0.518 0 0.938-0.42 0.938-0.938v-5.021c0-0.518-0.42-0.938-0.938-0.938-5.777 0-10.477 4.7-10.477 10.477s4.7 10.477 10.477 10.477c5.777 0 10.477-4.7 10.477-10.477v-9.112c1.866 0.995 3.942 1.514 6.092 1.514 0.518 0 0.938-0.42 0.938-0.938v-5.021c0-0.518-0.42-0.938-0.938-0.938zM28.108 12.011c-2.001-0.166-3.902-0.866-5.544-2.047-0.285-0.206-0.662-0.234-0.975-0.073s-0.51 0.482-0.51 0.834v10.798c0 4.743-3.859 8.602-8.602 8.602s-8.602-3.859-8.602-8.602c0-4.427 3.361-8.083 7.665-8.552v3.176c-2.563 0.446-4.519 2.687-4.519 5.376 0 3.009 2.447 5.456 5.456 5.456s5.456-2.448 5.456-5.456v-19.648h3.201c0.429 3.645 3.329 6.545 6.974 6.974z">
                                    </path>
                                </svg>
                            </span></a></li>
                </ul>
            </div>


            <div class="col-span-3 lg:col-span-2">
                <h3>روابط مهمة</h3>
                <div>
                    <div class="s-menu-footer-list"><a href="{{ route('website.privacy') }}" target="_self"
                            class="s-menu-footer-item">سياسة الخصوصية</a><a
                            href="{{ route('website.product.unreachable') }}"
                            target="_self" class="s-menu-footer-item">لا تستطيع الوصول للمنتج؟ ( قاموس البحث هنا
                            )</a><a href="{{ route('website.faq') }}" target="_self"
                            class="s-menu-footer-item">الأسئلة الشائعة</a><a
                            href="https://printnes.co/للشكاوي-والاقتراحات/page-2038658926" target="_self"
                            class="s-menu-footer-item">للشكاوي والاقتراحات</a><a
                            href="https://printnes.co/سياسة-الاستبدال-والاسترجاع/page-314905195" target="_self"
                            class="s-menu-footer-item">سياسة الاستبدال والاسترجاع</a><a
                            href="https://printnes.co/سياسة-الطباعة-والتصميم/page-1647732529" target="_self"
                            class="s-menu-footer-item">سياسة الطباعة والتصميم</a><a href="https://printnes.co/loyalty"
                            target="_self" class="s-menu-footer-item">نظام
                            المكافآت</a></div>
                </div>
            </div>

            <div class="col-span-3 lg:col-span-1">
                <h3 class="s-contacts-title">تواصل معنا</h3>
                <div class="s-contacts-list s-contacts-list-vertical">
                    <div id="contact-slot"><a href="https://printnes.co/whatsapp/send" class="s-contacts-item"><span
                                class="s-contacts-icon"><!-- Generated by IcoMoon.io -->
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                    viewBox="0 0 32 32">
                                    <title>whatsapp2</title>
                                    <path
                                        d="M27.281 4.65c-2.994-3-6.975-4.65-11.219-4.65-8.738 0-15.85 7.112-15.85 15.856 0 2.794 0.731 5.525 2.119 7.925l-2.25 8.219 8.406-2.206c2.319 1.262 4.925 1.931 7.575 1.931h0.006c0 0 0 0 0 0 8.738 0 15.856-7.113 15.856-15.856 0-4.238-1.65-8.219-4.644-11.219zM16.069 29.050v0c-2.369 0-4.688-0.637-6.713-1.837l-0.481-0.288-4.987 1.306 1.331-4.863-0.313-0.5c-1.325-2.094-2.019-4.519-2.019-7.012 0-7.269 5.912-13.181 13.188-13.181 3.519 0 6.831 1.375 9.319 3.862 2.488 2.494 3.856 5.8 3.856 9.325-0.006 7.275-5.919 13.188-13.181 13.188zM23.294 19.175c-0.394-0.2-2.344-1.156-2.706-1.288s-0.625-0.2-0.894 0.2c-0.262 0.394-1.025 1.288-1.256 1.556-0.231 0.262-0.462 0.3-0.856 0.1s-1.675-0.619-3.188-1.969c-1.175-1.050-1.975-2.35-2.206-2.744s-0.025-0.613 0.175-0.806c0.181-0.175 0.394-0.463 0.594-0.694s0.262-0.394 0.394-0.662c0.131-0.262 0.069-0.494-0.031-0.694s-0.894-2.15-1.219-2.944c-0.319-0.775-0.65-0.669-0.894-0.681-0.231-0.012-0.494-0.012-0.756-0.012s-0.694 0.1-1.056 0.494c-0.363 0.394-1.387 1.356-1.387 3.306s1.419 3.831 1.619 4.1c0.2 0.262 2.794 4.269 6.769 5.981 0.944 0.406 1.681 0.65 2.256 0.837 0.95 0.3 1.813 0.256 2.494 0.156 0.762-0.113 2.344-0.956 2.675-1.881s0.331-1.719 0.231-1.881c-0.094-0.175-0.356-0.275-0.756-0.475z">
                                    </path>
                                </svg>
                            </span><span class="unicode">+966554804857</span></a></div>
                    <div id="contact-slot"><a href="mailto:support@printnes.co" class="s-contacts-item"><span
                                class="s-contacts-icon"><!-- Generated by IcoMoon.io -->
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                    viewBox="0 0 32 32">
                                    <title>mail</title>
                                    <path
                                        d="M28 2.667h-24c-2.205 0-4 1.795-4 4v18.667c0 2.205 1.795 4 4 4h24c2.205 0 4-1.795 4-4v-18.667c0-2.205-1.795-4-4-4zM29.333 25.333c0 0.735-0.599 1.333-1.333 1.333h-24c-0.735 0-1.333-0.599-1.333-1.333v-12.685l10.54 4.865c0.888 0.409 1.84 0.613 2.793 0.613s1.907-0.204 2.793-0.615l10.54-4.864zM29.333 9.711l-11.657 5.38c-1.065 0.492-2.288 0.492-3.353 0l-11.656-5.38v-3.044c0-0.735 0.599-1.333 1.333-1.333h24c0.735 0 1.333 0.599 1.333 1.333z">
                                    </path>
                                </svg>
                            </span><span class="unicode">support@printnes.co</span></a></div>
                </div>
            </div>
        </div>

        <div class="container xl:px-0 grid lg:grid-flow-col lg:auto-cols-fr gap-6 pt-8">


            <div class="flex flex-col justify-center lg:items-end">
                <salla-apps-icons class=""></salla-apps-icons>
            </div>

        </div>

    </div>

    <div class="site-info-bar">
        <div
            class="flex flex-col-reverse lg:flex-row items-center justify-between py-4 lg:py-6 px-0 container text-center">
            <div class="text-sm">
                <p class="text-gray-400 mb-2.5 md:mb-0">الحقوق محفوظة | 2025
                    <a href="https://printnes.co" class="hover:text-primary" target="_blank" rel="noreferrer"
                        class="underline">Printnes</a>
                </p>
            </div>

            <div class="flex flex-col-reverse lg:flex-row">
                <div class="flex items-center justify-center gap-2 rtl:lg:ml-2 ltr:lg:mr-2 mb-3 lg:mb-0">
                    <p class="text-sm">الرقم الضريبي : 310595349100003</p>
                </div>

                <salla-payments></salla-payments>
            </div>
        </div>
    </div>
</footer>